// COSTANTI
const c = {
    TO_BE_STARTED : "TO_BE_STARTED",
    WAITING : "WAITING",
    DISCARDED : "DISCARDED",
    RUNNING : "RUNNING",
    COMPUTE_RESULT : "COMPUTE_RESULT",
    COMPLETED : "COMPLETED"
};

export default c