// COSTANTI
const c = {
    STATE_TO_BE_STARTED : "STATE_TO_BE_STARTED",
    STATE_WAITING : "STATE_WAITING",
    STATE_DISCARDED : "STATE_DISCARDED",
    STATE_EXECUTING : "STATE_EXECUTING",
    STATE_COMPUTE_RESULT : "STATE_COMPUTE_RESULT",
    STATE_COMPLETED : "STATE_COMPLETED"
};

export default c